name: ORT Image

on: [push]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout ORT
      uses: actions/checkout@v2
    - name: Checkout and run Scancode
      uses: actions/checkout@v2
      with:
        repository: Sheriff123/scancode-toolkit
        path: scancode-toolkit
    - name: Run Scancode toolkit
      run: |
        cd scancode-toolkit
        docker build -t scancode-toolkit .
        cd ..
        docker run scancode-toolkit --help

