name: ORT Image

on: [push]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Scancode
      uses: actions/checkout@v2
      with:
        repository: Sheriff123/scancode-toolkit
        path: scancode-toolkit
    - name: Run Scancode toolkit
      run: |
        cd scancode-toolkit
        docker build -t scancode-toolkit .
        cd ..
        docker run scancode-toolkit --help
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6.8' 
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.5.0'
    - name: Checkout ORT
      uses: actions/checkout@v2
      with:
        repository: Sheriff123/ort
        path: ort
    - name: test Scancode
      run: scancode --help
